T02 login/register
nurselaine/bobaTEAm pull request #7
Opened 2024-05-15 00:45 UTC by Blyatman0692

-- modified User.cs to BobaUser.cs to avoid naming conflict
-- added bobausers.json to store user info
-- added register page
-- added login page

2024-05-15 03:04 UTC, macnoblebk approved these changes

2024-05-16 09:05 UTC, nurselaine requested changes
Please merge after making changes!

2024-05-16 09:05 UTC, nurselaine commented on ContosoCrafts.WebSite/Models/BobaUser.cs
> +        private static string FilePath = "wwwroot/data/bobausers.json";
Can you change this to match this format

Path.Combine(WebHostEnvironment.WebRootPath, "data", "\<filename>\.json");

2024-05-16 09:05 UTC, nurselaine commented on ContosoCrafts.WebSite/Pages/Login.cshtml.cs
> +        if (!ModelState.IsValid)
What is ModelState?

2024-05-17 02:55 UTC, nurselaine approved these changes

2024-05-22 01:14 UTC, merged